import { StatusBar, StyleSheet } from 'react-native';

import { colors, radii, spacing, typography } from '../theme/tokens';

const statusBarInset = (StatusBar.currentHeight ?? 0) + 4;

export const appStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  shell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingBottom: spacing.xxl,
  },
  contentWithTabs: {
    paddingBottom: 96,
  },
  topHeader: {
    backgroundColor: colors.primaryDark,
    paddingHorizontal: 18,
    paddingTop: statusBarInset + spacing.md,
    paddingBottom: spacing.sm,
    gap: 6,
  },
  topHeaderHero: {
    backgroundColor: colors.backgroundAccent,
    paddingHorizontal: 18,
    paddingTop: statusBarInset + 12,
    paddingBottom: 14,
    gap: spacing.xs,
  },
  pageTitleLight: {
    color: '#FFFFFF',
    fontSize: typography.title,
    fontWeight: '700',
  },
  pageSubtitleLight: {
    color: '#FFFFFF',
    fontSize: typography.body,
  },
  heroCard: {
    marginHorizontal: 12,
    gap: spacing.xs,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  brandBadge: {
    width: 26,
    height: 26,
    borderRadius: radii.pill,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandBadgeText: {
    color: '#FFFFFF',
    fontSize: typography.body,
    fontWeight: '700',
  },
  brandTextBlock: {
    gap: spacing.xxs,
    flex: 1,
  },
  brandTitle: {
    color: '#047857',
    fontSize: typography.title,
    fontWeight: '700',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pinDot: {
    width: 10,
    height: 10,
    borderWidth: 1,
    borderColor: colors.textMuted,
    borderRadius: radii.pill,
  },
  locationText: {
    color: colors.textMuted,
    fontSize: typography.body,
  },
  nextCollectionCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: spacing.xs,
  },
  nextCollectionTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  nextCollectionEyebrow: {
    color: colors.primaryDark,
    fontSize: typography.bodyLg,
    fontWeight: '700',
  },
  nextCollectionTitle: {
    color: colors.text,
    fontSize: typography.hero,
    fontWeight: '700',
  },
  nextCollectionSubtitle: {
    color: colors.textMuted,
    fontSize: typography.bodyLg,
    lineHeight: 20,
  },
  timePill: {
    minWidth: 70,
    borderRadius: 10,
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignItems: 'center',
  },
  timePillText: {
    color: colors.primaryDark,
    fontSize: typography.bodyLg,
    fontWeight: '700',
  },
  divider: {
    height: 1,
    backgroundColor: colors.borderSoft,
  },
  wasteInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  wasteInlineTextLight: {
    color: colors.text,
    fontSize: typography.bodyLg,
  },
  section: {
    marginTop: spacing.md,
    marginHorizontal: 18,
    gap: spacing.sm,
  },
  sectionCompact: {
    marginTop: spacing.md,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: typography.hero,
    fontWeight: '700',
  },
  sectionTitleSmall: {
    color: colors.text,
    fontSize: typography.titleSm,
    fontWeight: '700',
  },
  sectionBody: {
    color: colors.textMuted,
    fontSize: typography.bodyLg,
    lineHeight: 20,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.sm,
  },
  scheduleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  scheduleCardMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
    paddingRight: spacing.sm,
  },
  scheduleCardText: {
    flex: 1,
    gap: 2,
  },
  scheduleTitle: {
    color: '#5A5A5A',
    fontSize: typography.bodySm,
    fontWeight: '500',
  },
  scheduleMeta: {
    color: colors.textMuted,
    fontSize: typography.bodyLg,
  },
  scheduleTime: {
    color: colors.textMuted,
    fontSize: typography.bodyLg,
  },
  wasteBadge: {
    width: 40,
    height: 40,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wasteBadgeText: {
    color: '#9A3412',
    fontSize: typography.bodySm,
    fontWeight: '700',
  },
  wasteBadgeTextCyan: {
    color: '#0891B2',
  },
  wasteBadgeTextRed: {
    color: '#DC2626',
  },
  wetIcon: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wetIconLid: {
    width: 16,
    height: 3,
    borderRadius: radii.pill,
    backgroundColor: '#9A3412',
    marginBottom: 2,
  },
  wetIconBin: {
    width: 14,
    height: 15,
    borderRadius: 3,
    borderWidth: 1.5,
    borderColor: '#9A3412',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  wetIconScrap: {
    width: 7,
    height: 4,
    borderRadius: 4,
    backgroundColor: '#9A3412',
    transform: [{ rotate: '-18deg' }],
  },
  wetIconScrapSmall: {
    width: 4,
    height: 4,
    borderRadius: radii.pill,
    backgroundColor: '#9A3412',
  },
  dryIcon: {
    width: 20,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dryIconSheet: {
    width: 15,
    height: 18,
    borderRadius: 3,
    borderWidth: 1.5,
    borderColor: '#0891B2',
    backgroundColor: 'transparent',
  },
  dryIconLineLong: {
    width: 9,
    height: 2,
    borderRadius: radii.pill,
    backgroundColor: '#0891B2',
    position: 'absolute',
    top: 8,
  },
  dryIconLineShort: {
    width: 6,
    height: 2,
    borderRadius: radii.pill,
    backgroundColor: '#0891B2',
    position: 'absolute',
    top: 13,
  },
  locationHelpIcon: {
    width: 21,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationHelpPin: {
    width: 14,
    height: 14,
    borderRadius: 8,
    borderBottomRightRadius: 2,
    backgroundColor: colors.primaryDark,
    transform: [{ rotate: '45deg' }],
    position: 'absolute',
    top: 1,
  },
  locationHelpHole: {
    width: 5,
    height: 5,
    borderRadius: radii.pill,
    backgroundColor: colors.primarySoft,
    position: 'absolute',
    top: 5,
  },
  locationHelpBase: {
    width: 16,
    height: 3,
    borderRadius: radii.pill,
    backgroundColor: colors.primaryDark,
    position: 'absolute',
    bottom: 2,
    opacity: 0.35,
  },
  tipRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  tipBullet: {
    color: colors.primary,
    fontSize: typography.body,
    lineHeight: 18,
  },
  tipText: {
    color: '#325190',
    fontSize: typography.bodyLg,
    lineHeight: 20,
    flex: 1,
  },
  tipLink: {
    color: colors.info,
    fontSize: typography.body,
  },
  alertCard: {
    marginHorizontal: 18,
    marginTop: spacing.md,
    backgroundColor: '#FFF2EC',
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: '#F0CBB7',
    padding: spacing.md,
    gap: spacing.xs,
  },
  alertTitle: {
    color: '#D9480F',
    fontSize: typography.titleSm,
    fontWeight: '700',
  },
  alertText: {
    color: '#7C2D12',
    fontSize: typography.bodyLg,
    lineHeight: 20,
  },
  calendarMonthRow: {
    marginTop: spacing.md,
    marginHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  monthArrow: {
    color: colors.text,
    fontSize: 28,
    lineHeight: 28,
  },
  monthArrowButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthLabel: {
    color: colors.text,
    fontSize: typography.hero,
    fontWeight: '700',
  },
  calendarCard: {
    marginTop: spacing.md,
    marginHorizontal: 18,
    backgroundColor: colors.surface,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    gap: spacing.sm,
  },
  weekdayRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
  },
  weekdayCell: {
    flex: 1,
    textAlign: 'center',
    color: colors.textMuted,
    fontSize: typography.body,
    fontWeight: '600',
  },
  weekRow: {
    flexDirection: 'row',
    gap: 6,
  },
  dayCell: {
    flex: 1,
    minHeight: 40,
    borderRadius: radii.xs,
    borderWidth: 1,
    borderColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingVertical: 5,
  },
  dayCellCollection: {
    borderColor: colors.primary,
  },
  dayNumber: {
    fontSize: typography.bodyLg,
  },
  dayMarker: {
    fontSize: typography.caption,
    fontWeight: '700',
  },
  dayCellMuted: {
    opacity: 0.65,
  },
  legendList: {
    marginHorizontal: 18,
    marginTop: spacing.md,
    gap: spacing.md,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  legendMetaBlock: {
    flex: 1,
    gap: 2,
  },
  legendTitle: {
    color: '#5A5A5A',
    fontSize: typography.titleSm,
    fontWeight: '500',
  },
  legendText: {
    color: colors.textMuted,
    fontSize: typography.bodyLg,
    lineHeight: 18,
  },
  noteCard: {
    marginHorizontal: 18,
    marginTop: spacing.lg,
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: '#BFD7FF',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  noteCardInline: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: '#BFD7FF',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  noteText: {
    color: colors.info,
    fontSize: typography.body,
  },
  listBlock: {
    gap: spacing.sm,
  },
  nestedCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.xs,
  },
  body: {
    color: colors.text,
    fontSize: typography.bodyLg,
    lineHeight: 20,
  },
  bodyStrong: {
    color: colors.text,
    fontSize: typography.bodyLg,
    fontWeight: '700',
  },
  meta: {
    color: colors.textMuted,
    fontSize: typography.bodyLg,
    lineHeight: 18,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  choiceChip: {
    borderRadius: radii.pill,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  choiceChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  choiceChipText: {
    color: colors.text,
    fontSize: typography.bodyLg,
    fontWeight: '600',
  },
  choiceChipTextActive: {
    color: '#FFFFFF',
  },
  formGroup: {
    gap: spacing.xs,
  },
  inputLabel: {
    color: colors.text,
    fontSize: typography.bodyLg,
    fontWeight: '600',
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.sm,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    color: colors.text,
    fontSize: typography.bodyLg,
  },
  buttonPrimary: {
    backgroundColor: colors.primary,
    borderRadius: radii.sm,
    paddingHorizontal: 18,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonPrimaryText: {
    color: '#FFFFFF',
    fontSize: typography.bodyLg,
    fontWeight: '700',
  },
  buttonSecondary: {
    backgroundColor: '#FFFFFF',
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 18,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonSecondaryText: {
    color: colors.text,
    fontSize: typography.bodyLg,
    fontWeight: '600',
  },
  signOutButton: {
    backgroundColor: '#FEE2E2',
    borderRadius: radii.sm,
    paddingHorizontal: 18,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  signOutButtonText: {
    color: '#DC2626',
    fontSize: typography.bodyLg,
    fontWeight: '700',
  },
  preferenceToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  toggleTrack: {
    width: 48,
    height: 28,
    borderRadius: radii.pill,
    backgroundColor: colors.borderSoft,
    padding: 3,
    justifyContent: 'center',
  },
  toggleTrackActive: {
    backgroundColor: colors.primary,
  },
  toggleThumb: {
    width: 22,
    height: 22,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
  },
  toggleThumbActive: {
    alignSelf: 'flex-end',
  },
  errorText: {
    color: '#DC2626',
    fontSize: typography.bodyLg,
  },
  loginWrap: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingTop: statusBarInset + spacing.lg,
    paddingBottom: spacing.xl,
    gap: spacing.md,
    backgroundColor: colors.backgroundAccent,
  },
  authHero: {
    gap: spacing.sm,
  },
  eyebrow: {
    color: colors.primaryDark,
    fontSize: typography.body,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  title: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '700',
  },
  subtitle: {
    color: colors.textMuted,
    fontSize: typography.bodyLg,
    lineHeight: 20,
  },
  loadingWrap: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingTop: statusBarInset,
    backgroundColor: colors.backgroundAccent,
  },
  loadingCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 14,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
  },
  tabButton: {
    alignItems: 'center',
    gap: 4,
    minWidth: 64,
  },
  tabIcon: {
    width: 28,
    height: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIconActive: {
    backgroundColor: colors.primarySoft,
  },
  tabButtonText: {
    color: colors.textMuted,
    fontSize: typography.caption,
  },
  tabButtonTextActive: {
    color: colors.primary,
  },
  iconShapeActive: {
    backgroundColor: colors.primary,
  },
  iconStrokeActive: {
    borderColor: colors.primary,
  },
  homeIcon: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  homeIconRoof: {
    width: 13,
    height: 13,
    borderRadius: 2,
    backgroundColor: colors.textMuted,
    transform: [{ rotate: '45deg' }],
    position: 'absolute',
    top: 1,
  },
  homeIconBase: {
    width: 15,
    height: 10,
    borderRadius: 3,
    backgroundColor: colors.textMuted,
  },
  calendarIconBox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: colors.textMuted,
    overflow: 'hidden',
  },
  calendarIconTop: {
    height: 5,
    backgroundColor: colors.textMuted,
  },
  calendarIconGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 5,
    paddingHorizontal: 3,
  },
  calendarIconDot: {
    width: 3,
    height: 3,
    borderRadius: radii.pill,
    backgroundColor: colors.textMuted,
  },
  tipsIcon: {
    width: 20,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tipsIconBubble: {
    width: 18,
    height: 14,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: colors.textMuted,
    justifyContent: 'center',
    gap: 3,
    paddingHorizontal: 4,
  },
  tipsIconLineLong: {
    height: 2,
    width: 9,
    borderRadius: radii.pill,
    backgroundColor: colors.textMuted,
  },
  tipsIconLineShort: {
    height: 2,
    width: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.textMuted,
  },
  tipsIconTail: {
    width: 6,
    height: 6,
    borderRadius: 1,
    backgroundColor: colors.textMuted,
    transform: [{ rotate: '45deg' }],
    position: 'absolute',
    left: 4,
    bottom: 0,
  },
  settingsIcon: {
    width: 20,
    height: 18,
    justifyContent: 'space-around',
  },
  settingsIconCircle: {
    width: 8,
    height: 8,
    borderRadius: radii.pill,
    borderWidth: 1.5,
    borderColor: colors.textMuted,
    position: 'absolute',
    right: 2,
    top: 0,
    zIndex: 1,
    backgroundColor: colors.surface,
  },
  settingsIconSliderTop: {
    height: 2,
    borderRadius: radii.pill,
    backgroundColor: colors.textMuted,
  },
  settingsIconSliderBottom: {
    height: 2,
    borderRadius: radii.pill,
    backgroundColor: colors.textMuted,
  },
});
