import { StatusBar, StyleSheet } from 'react-native';

import { colors, radii, spacing, typography } from '../theme/tokens';

const statusBarInset = (StatusBar.currentHeight ?? 0) + 4;

export const appStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  shell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingBottom: spacing.xxl,
  },
  contentWithTabs: {
    paddingBottom: 96,
  },
  topHeader: {
    backgroundColor: colors.primaryDark,
    paddingHorizontal: 18,
    paddingTop: statusBarInset + spacing.md,
    paddingBottom: spacing.sm,
    gap: 6,
  },
  topHeaderHero: {
    backgroundColor: colors.backgroundAccent,
    paddingHorizontal: 18,
    paddingTop: statusBarInset + 18,
    paddingBottom: 20,
    gap: spacing.sm,
  },
  pageTitleLight: {
    color: '#FFFFFF',
    fontSize: typography.title,
    fontWeight: '700',
  },
  pageSubtitleLight: {
    color: '#FFFFFF',
    fontSize: typography.body,
  },
  heroCard: {
    marginHorizontal: 18,
    gap: spacing.sm,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  brandBadge: {
    width: 26,
    height: 35,
    borderRadius: radii.pill,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandBadgeText: {
    color: '#FFFFFF',
    fontSize: typography.body,
    fontWeight: '700',
  },
  brandTextBlock: {
    gap: spacing.xxs,
    flex: 1,
  },
  brandTitle: {
    color: '#047857',
    fontSize: typography.hero,
    fontWeight: '700',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pinDot: {
    width: 10,
    height: 10,
    borderWidth: 1,
    borderColor: colors.textMuted,
    borderRadius: radii.pill,
  },
  locationText: {
    color: colors.textMuted,
    fontSize: typography.body,
  },
  nextCollectionCard: {
    backgroundColor: colors.primary,
    borderRadius: radii.md,
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: spacing.sm,
  },
  nextCollectionTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  nextCollectionEyebrow: {
    color: '#FFFFFF',
    fontSize: typography.titleSm,
    fontWeight: '700',
  },
  nextCollectionTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '700',
  },
  nextCollectionSubtitle: {
    color: '#EAF9F3',
    fontSize: typography.bodyLg,
  },
  timePill: {
    minWidth: 78,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.18)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: 'center',
  },
  timePillText: {
    color: '#FFFFFF',
    fontSize: typography.bodyLg,
    fontWeight: '700',
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  wasteInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  wasteInlineTextLight: {
    color: '#FFFFFF',
    fontSize: typography.bodyLg,
  },
  section: {
    marginTop: spacing.lg,
    marginHorizontal: 18,
    gap: spacing.sm,
  },
  sectionCompact: {
    marginTop: spacing.md,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: typography.hero,
    fontWeight: '700',
  },
  sectionTitleSmall: {
    color: colors.text,
    fontSize: typography.titleSm,
    fontWeight: '700',
  },
  sectionBody: {
    color: colors.textMuted,
    fontSize: typography.bodyLg,
    lineHeight: 20,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.sm,
  },
  scheduleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  scheduleCardMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
    paddingRight: spacing.sm,
  },
  scheduleCardText: {
    flex: 1,
    gap: 2,
  },
  scheduleTitle: {
    color: '#5A5A5A',
    fontSize: typography.bodySm,
    fontWeight: '500',
  },
  scheduleMeta: {
    color: colors.textMuted,
    fontSize: typography.bodyLg,
  },
  scheduleTime: {
    color: colors.textMuted,
    fontSize: typography.bodyLg,
  },
  wasteBadge: {
    width: 40,
    height: 40,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wasteBadgeText: {
    color: '#9A3412',
    fontSize: typography.bodySm,
    fontWeight: '700',
  },
  wasteBadgeTextCyan: {
    color: '#0891B2',
  },
  wasteBadgeTextRed: {
    color: '#DC2626',
  },
  tipsCard: {
    backgroundColor: '#EEF4FF',
    borderColor: '#BFD7FF',
  },
  tipRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  tipBullet: {
    color: colors.primary,
    fontSize: typography.body,
    lineHeight: 18,
  },
  tipText: {
    color: '#325190',
    fontSize: typography.bodyLg,
    lineHeight: 20,
    flex: 1,
  },
  tipLink: {
    color: colors.info,
    fontSize: typography.body,
  },
  alertCard: {
    marginHorizontal: 18,
    marginTop: spacing.md,
    backgroundColor: '#FFF2EC',
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: '#F0CBB7',
    padding: spacing.md,
    gap: spacing.xs,
  },
  alertTitle: {
    color: '#D9480F',
    fontSize: typography.titleSm,
    fontWeight: '700',
  },
  alertText: {
    color: '#7C2D12',
    fontSize: typography.bodyLg,
    lineHeight: 20,
  },
  calendarMonthRow: {
    marginTop: spacing.md,
    marginHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  monthArrow: {
    color: colors.text,
    fontSize: 28,
    lineHeight: 28,
  },
  monthLabel: {
    color: colors.text,
    fontSize: typography.hero,
    fontWeight: '700',
  },
  calendarCard: {
    marginTop: spacing.md,
    marginHorizontal: 18,
    backgroundColor: colors.surface,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    gap: spacing.sm,
  },
  weekdayRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
  },
  weekdayCell: {
    flex: 1,
    textAlign: 'center',
    color: colors.textMuted,
    fontSize: typography.body,
    fontWeight: '600',
  },
  weekRow: {
    flexDirection: 'row',
    gap: 6,
  },
  dayCell: {
    flex: 1,
    minHeight: 40,
    borderRadius: radii.xs,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingVertical: 5,
  },
  dayNumber: {
    fontSize: typography.bodyLg,
  },
  dayMarker: {
    fontSize: typography.caption,
    fontWeight: '700',
  },
  dayCellMuted: {
    opacity: 0.65,
  },
  legendList: {
    marginHorizontal: 18,
    marginTop: spacing.md,
    gap: spacing.md,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  legendMetaBlock: {
    flex: 1,
    gap: 2,
  },
  legendTitle: {
    color: '#5A5A5A',
    fontSize: typography.titleSm,
    fontWeight: '500',
  },
  legendText: {
    color: colors.textMuted,
    fontSize: typography.bodyLg,
    lineHeight: 18,
  },
  noteCard: {
    marginHorizontal: 18,
    marginTop: spacing.lg,
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: '#BFD7FF',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  noteText: {
    color: colors.info,
    fontSize: typography.body,
  },
  listBlock: {
    gap: spacing.sm,
  },
  nestedCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.xs,
  },
  body: {
    color: colors.text,
    fontSize: typography.bodyLg,
    lineHeight: 20,
  },
  bodyStrong: {
    color: colors.text,
    fontSize: typography.bodyLg,
    fontWeight: '700',
  },
  meta: {
    color: colors.textMuted,
    fontSize: typography.bodyLg,
    lineHeight: 18,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  choiceChip: {
    borderRadius: radii.pill,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  choiceChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  choiceChipText: {
    color: colors.text,
    fontSize: typography.bodyLg,
    fontWeight: '600',
  },
  choiceChipTextActive: {
    color: '#FFFFFF',
  },
  formGroup: {
    gap: spacing.xs,
  },
  inputLabel: {
    color: colors.text,
    fontSize: typography.bodyLg,
    fontWeight: '600',
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.sm,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    color: colors.text,
    fontSize: typography.bodyLg,
  },
  buttonPrimary: {
    backgroundColor: colors.primary,
    borderRadius: radii.sm,
    paddingHorizontal: 18,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonPrimaryText: {
    color: '#FFFFFF',
    fontSize: typography.bodyLg,
    fontWeight: '700',
  },
  buttonSecondary: {
    backgroundColor: '#FFFFFF',
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 18,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonSecondaryText: {
    color: colors.text,
    fontSize: typography.bodyLg,
    fontWeight: '600',
  },
  signOutButton: {
    backgroundColor: '#FEE2E2',
    borderRadius: radii.sm,
    paddingHorizontal: 18,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  signOutButtonText: {
    color: '#DC2626',
    fontSize: typography.bodyLg,
    fontWeight: '700',
  },
  errorText: {
    color: '#DC2626',
    fontSize: typography.bodyLg,
  },
  loginWrap: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingTop: statusBarInset + spacing.lg,
    paddingBottom: spacing.xl,
    gap: spacing.md,
    backgroundColor: colors.backgroundAccent,
  },
  authHero: {
    gap: spacing.sm,
  },
  eyebrow: {
    color: colors.primaryDark,
    fontSize: typography.body,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  title: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '700',
  },
  subtitle: {
    color: colors.textMuted,
    fontSize: typography.bodyLg,
    lineHeight: 20,
  },
  loadingWrap: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingTop: statusBarInset,
    backgroundColor: colors.backgroundAccent,
  },
  loadingCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 14,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
  },
  tabButton: {
    alignItems: 'center',
    gap: 4,
    minWidth: 64,
  },
  tabIcon: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: colors.textMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIconActive: {
    borderColor: colors.primary,
  },
  tabIconText: {
    color: colors.textMuted,
    fontSize: typography.caption,
    fontWeight: '700',
  },
  tabIconTextActive: {
    color: colors.primary,
  },
  tabButtonText: {
    color: colors.textMuted,
    fontSize: typography.caption,
  },
  tabButtonTextActive: {
    color: colors.primary,
  },
});
